### ISSUE TITLE
sqllite插入数据报错

### ISSUE THREAD

**Issue by zhaozuolin** [HWYWL/spring-boot-2.x-examples#3]
SQL: insert into baike      ( book,                       tag,                       good,                       bad,                       name,                       gender,                       goldCoin,                       status,                       crateDate,                       updateDate )       values ( ?,                       ?,                       ?,                       ?,                       ?,                       ?,                       ?,                       ?,                       ?,                       ? )识别不了？

**Comment by zhaozuolin** [comment]
A NOT NULL constraint failed (NOT NULL constraint failed: baike.id)

**Comment by zhaozuolin** [comment]
非空约束失败，即使我添加了id的值还是报错。

**Comment by zhaozuolin** [comment]
其实解决了。

**Comment by HWYWL** [comment]
已修复，还更新了新的特性
